version: '3.8'

services:
  postgres:
    container_name: 'postgres'
    image: postgres
    volumes:
      - /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
  
  server:
    container_name: server
    build: .
    depends_on:
      - postgres
